### ISSUE TITLE
bug when used with killable enemies

### ISSUE THREAD

**Issue by 1410677474** [ZehsTeam/Lethal-Company-ToilHead#1]
Mods：KillableEnemies

![22b0d9e8f3912443bfb681c7d33b6c7](https://github.com/ZehsTeam/Lethal-Company-ToilHead/assets/163803538/685cd149-4c55-46bf-a3e6-ed982bf246bf)

**Comment by 1410677474** [comment]
![Uploading 22b0d9e8f3912443bfb681c7d33b6c7.jpg…]()

**Comment by ZehsTeam** [comment]
@1410677474 This is now fixed in [v1.1.0+](https://thunderstore.io/c/lethal-company/p/Zehs/ToilHead/), [2034518](https://github.com/ZehsTeam/Lethal-Company-ToilHead/commit/20345182a60adad7745aa428cfffb462c2a2dd7d)
