### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Solaire99** [ZehsTeam/Lethal-Company-ToilHead#2]
Great mod you got here. If you could collab with the missile turret guy to get a Missile Turret Coilhead that would be hilarious. Sorry for the issue popup. Didn't know where else to comment on this site.

**Comment by ZehsTeam** [comment]
@Solaire99 I love that idea hahaha. I was thinking about that earlier.

**Comment by ZehsTeam** [comment]
I'm unsure how to implement this without copying all their assets because the missile turrets are their own thing. Though I might revisit this in the future.
